language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t alperarabaci/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true alperarabaci/react-test npm test
    
after_success:
    - docker build -t alperarabaci/multi-client ./client
    - docker build -t alperarabaci/multi-nginx ./nginx
    - docker build -t alperarabaci/multi-server ./server
    - docker build -t alperarabaci/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push alperarabaci/multi-client
    - docker push alperarabaci/multi-nginx 
    - docker push alperarabaci/multi-server
    - docker push alperarabaci/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-479850712799
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id:$AWS_ACCESS_KEY     
    secret_access_key:
        secure:$AWS_SECRET_KEY     